# Generated by Django 6.0.6 on 2026-07-21 07:10

import ors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0005_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'sos_subject',
            },
            bases=(ors.models.DropdownItem, models.Model),
        ),
    ]
