# Generated by Django 6.0.6 on 2026-07-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0006_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='duration',
        ),
    ]
