# Generated by Django 6.0.6 on 2026-07-21 14:33

import ors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0007_remove_subject_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('student_id', models.IntegerField(default=0)),
                ('student_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('maths', models.IntegerField()),
            ],
            options={
                'db_table': 'sos_marksheet',
            },
            bases=(ors.models.DropdownItem, models.Model),
        ),
    ]
