# Generated by Django 6.0.6 on 2026-07-21 14:51

import ors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0008_marksheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('subject_id', models.IntegerField()),
                ('subject_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sos_timetable',
            },
            bases=(ors.models.DropdownItem, models.Model),
        ),
    ]
